[32m[I 2025-01-26 17:10:38,887][0m A new study created in memory with name: no-name-71d9bb85-4abd-449f-b9b1-80a356e50716[0m
[33m[W 2025-01-26 17:10:49,614][0m Trial 0 failed with parameters: {'observation_period_num': 195, 'train_rates': 0.6634078293183041, 'learning_rate': 2.995199106847625e-05, 'batch_size': 138, 'step_size': 14, 'gamma': 0.9646129872528424} because of the following error: KeyboardInterrupt().[0m
Traceback (most recent call last):
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/Transformersingle.py", line 203, in <lambda>
    study.optimize(lambda t: objective(t, comp, depth, dim), n_trials=50) #check
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/Transformersingle.py", line 98, in objective
    model, _, valid_loss = train(
                           ^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/src/train.py", line 43, in train
    total_loss_train += loss.item() * data.size(0)
                        ^^^^^^^^^^^
KeyboardInterrupt
[33m[W 2025-01-26 17:10:49,628][0m Trial 0 failed with value None.[0m
Traceback (most recent call last):
  File "/data/student/k2110261/Multi-iTransformer/Transformersingle.py", line 203, in <module>
    study.optimize(lambda t: objective(t, comp, depth, dim), n_trials=50) #check
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home2/y2021/k2110261/.conda/envs/tensorflow/lib/python3.11/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/Transformersingle.py", line 203, in <lambda>
    study.optimize(lambda t: objective(t, comp, depth, dim), n_trials=50) #check
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/Transformersingle.py", line 98, in objective
    model, _, valid_loss = train(
                           ^^^^^^
  File "/data/student/k2110261/Multi-iTransformer/src/train.py", line 43, in train
    total_loss_train += loss.item() * data.size(0)
                        ^^^^^^^^^^^
KeyboardInterrupt
